server:
  port: 8001

# spring相关配置
spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 采样率值介于 0 到 1 之间,1 表示全部采集
      probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        # mysql 驱动包
    url: jdbc:mysql://localhost:3306/springcloud_atiguigu?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456

#  cloud:
#    inetutils:
#    timeout-seconds: 10
#    druid:
#      validation-query: select 1
#      test-on-borrow: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.zyj.springCloud.entities # 所有Entity别名所在的包


# eureka 配置
eureka:
  client:
    # 表示是否将自己注册进eureka  默认为true
    register-with-eureka: true
    # 是否从eurekaServer中抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配置ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 单机版
#      defaultZone: http://localhost:7001/eureka
      # 集群版
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  # actuator 微服务信息完善
  instance:
    instance-id: payment8001
    prefer-ip-address: true   # 访问路径可以显示IP地址
    # Eureka客户端向服务端发送心跳的时间间隔,单位为秒(默认是30秒)
    lease-renewal-interval-in-seconds: 1
    # Eureka服务端在收到最后一次心跳后等待时间上限,单位为秒(默认是90秒),超时则剔除服务
    lease-expiration-duration-in-seconds: 2
