server:
  port: 3344

spring:
  application:
    name: cloud-config-center   # 注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jiang-zyj/springcloud-config.git    # Github上面的git仓库名字
          # 搜索目录
          search-paths:
            - springcloud-config
          username: jiang-zyj
          password: 0202dced
          skip-ssl-validation: true
        # 读取分支
        label: master
  # rabbitmq 相关配置
  rabbitmq:
    host: 192.168.241.134
    port: 5672
    username: admin
    password: 123



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka


# rabbitmq 相关配置，暴露 bus 刷新配置的端点
management:
  endpoints:    # 暴露 bus 刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'

