server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  # 配置动态路由
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route                   # 路由的ID，没有固定规则，但是要唯一，建议配合服务名
#          uri: http://localhost:8001            # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service            # 匹配后提供服务的路由地址

          predicates:
            - Path=/payment/get/**              # 断言，路径相匹配的进行路由

        - id: payment_route2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service   # 匹配后提供服务的路由地址
          # 演示Predicate断言
          predicates:
            - Path=/payment/lb/**
#            - After=2021-08-07T18:20:53.585+08:00[Asia/Shanghai]
#            - Before=After=2021-08-07T18:20:53.585+08:00[Asia/Shanghai]
#            - Between=After=2021-08-07T18:20:53.585+08:00[Asia/Shanghai],After=2021-08-07T18:25:53.585+08:00[Asia/Shanghai]
#            - Cookie=username, zzyy      # cookie，键值对
#            - Header=X-Request-Id, \d+    # 请求头要有X-Request-Id属性并且值为整数的正则表达式
#            - Method=Get                  # 请求必须为Get
#            - Query=username, \d+         # 要有参数名username并且值为整数才能进行路由

          # 演示 Filter
          filters:
            - AddRequestHeader=X-Request-red, blue # 过滤器工厂会在匹配的请求头上加上一对请求头，名称为X-Request-red，值为blue

eureka:
  instance:
    hostname: cloud-gateway-service
  # 服务提供者provider注册进eureka
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka